# Generated by Django 4.0.3 on 2022-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=1)),
                ('age', models.DateField()),
            ],
        ),
    ]
