# Generated by Django 4.0.3 on 2022-04-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_category_alter_user_email_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
