# Generated by Django 4.0.3 on 2022-04-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_rename_item_id_order_item_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
