# Generated by Django 4.0.3 on 2022-04-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_rename_user_id_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=1)),
                ('comment', models.CharField(max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.user')),
            ],
        ),
    ]
