# Generated by Django 4.0.3 on 2022-05-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
