# Generated by Django 4.0.3 on 2022-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_item_quantity_alter_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='d', max_length=1),
        ),
    ]
