# Generated by Django 4.0.3 on 2022-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
